---
title: "Eval Landsharc sims"
author: "Katie Lotterhos"
date: "May 24, 2016"
output: html_document
---
### Load packages and data
```{r setup, include=FALSE}
#setwd("/Users/katie/Desktop/MINOTAUReval")
source("evalsims/ComparePlot2.R")
source("evalsims/distanceFunctionsOther.R")
source("evalsims/getEmpiricalP3_BH.R")
source("evalsims/Getdf.R")


if(!("devtools" %in% installed.packages())){install.packages("devtools", dependencies=TRUE)}
if(!("rrcovNA" %in% installed.packages())){install.packages("rrcovNA")}

library(qvalue)
library(rrcovNA)
library(devtools)
install_github("NESCent/MINOTAUR", ref='develop')#, build_vignettes=TRUE)
library(MINOTAUR)

headdir <- "data/KatieSims/"
resultsdir <- "~/Desktop/MINOTAUReval/results/"
filelist <- list.files(headdir)
filelist <- filelist[-55]
length(filelist)
if (!length(filelist)==72){print("Errr: missing simulation files")}

sessionInfo()
```

### Loop through each dataset
The following chunk of code does for each dataset:
1) calculate multivariate distances based on default covariance matrix
2) compares covariance matrix estimated from just neutral loci to covariance matrix on all data and MCD/PCS estimate of covariance

```{r}
cov_summary <- data.frame(filename=NA, 
                Comparison1=NA, Comparison2=NA, 
                ScatterDiff=NA, LocationDiff=NA,
                alpha=NA, method=NA)
head(cov_summary)

for (i in 1:length(filelist)){
  print(c(i, filelist[i]))
  
  infile <- paste(headdir, filelist[i], sep="")
  dat <- read.table(infile, header=TRUE)
  dat2 <- dat[dat$UseSNP,]
  cols <- which(names(dat) %in% c("rho", "log.bf", "xtx", "TW.Zscore"))

  # Covariance of all loci
    (Sall <- cov(dat2[,cols]))
    (Sall_mean <- colMeans(dat2[,cols]))
    
  # Covariance of neutral loci
    (Sneut <- cov(dat2[dat2$s_high==0,cols]))
    (Sneut_mean <- colMeans(dat2[dat2$s_high==0,cols]))
        
  # Covariance of MCD 51
    S_mcd51 <- CovNAMcd(dat2[,cols], alpha=0.51)
    S_mcd51@cov
    S_mcd51@center
  # Covariance of MCD 75
    S_mcd75 <- CovNAMcd(dat2[,cols], alpha=0.75)
    S_mcd75@cov
    S_mcd75@center
    #S_mcd75
  # Covariance of MCD 90
    S_mcd90 <- CovNAMcd(dat2[,cols], alpha=0.90)
    S_mcd90@cov
    S_mcd90@center
    #S_mcd99    
    
  # Covariance of PCS 51
    S_pcs51 <- FastPCS(dat2[,cols], alpha=0.51)
    S_pcs51$cov
    S_pcs51$center
  # Covariance of PCS 75
    S_pcs75 <- FastPCS(dat2[,cols], alpha=0.75)
    S_pcs75$cov
    S_pcs75$center
    #S_mcd75
  # Covariance of PCS 90
    S_pcs90 <- FastPCS(dat2[,cols], alpha=0.90)
    S_pcs90$cov
    S_pcs90$center
    
  ### Comparisons with neutral #########
    cov_summary<- rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "All",
      ScatterDiff = mean((Sall-Sneut)^2),
      LocationDiff = mean((Sall_mean-Sneut_mean)^2),
      alpha=NA, method=NA
    ))
    ### MCD
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "MCD 0.51",
      ScatterDiff= mean((Sneut-S_mcd51@cov)^2),
      LocationDiff= mean((Sneut_mean-S_mcd51@center)^2),
      alpha=0.51, method="MCD"
    ))
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "MCD 0.75",
      ScatterDiff= mean((Sneut-S_mcd75@cov)^2),
      LocationDiff= mean((Sneut_mean-S_mcd75@center)^2),
      alpha=0.75, method="MCD"
    ))
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "MCD 0.90",
      ScatterDiff= mean((Sneut-S_mcd90@cov)^2),
      LocationDiff= mean((Sneut_mean-S_mcd90@center)^2),
      alpha=0.9, method="MCD"
    ))
    ### PCS
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "PCS 0.51",
      ScatterDiff= mean((Sneut-S_pcs51$cov)^2),
      LocationDiff= mean((Sneut_mean-S_pcs51$center)^2),
      alpha=0.51, method="PCS"
    ))
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "PCS 0.75",
      ScatterDiff= mean((Sneut-S_pcs75$cov)^2),
      LocationDiff= mean((Sneut_mean-S_pcs75$center)^2),
      alpha=0.75, method="PCS"
    ))
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "Neutral",
      Comparison2= "PCS 0.90",
      ScatterDiff= mean((Sneut-S_pcs90$cov)^2),
      LocationDiff= mean((Sneut_mean-S_pcs90$center)^2),
      alpha=0.90, method="PCS"
    ))
    
    ### Comparisons with All
    cov_summary<- rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "All",
      Comparison2= "Neutral",
      ScatterDiff = mean((Sall-Sneut)^2),
      LocationDiff = mean((Sall_mean-Sneut_mean)^2),
      alpha=NA, method=NA
    )) #this is redundant, for plotting only
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "All",
      Comparison2= "MCD 0.75",
      ScatterDiff= mean((Sall-S_mcd75@cov)^2),
      LocationDiff= mean((Sall_mean-S_mcd75@center)^2),
      alpha=0.75, method="MCD"
    ))
    cov_summary<-rbind(cov_summary, data.frame(
      filename=filelist[i],
      Comparison1= "All",
      Comparison2= "MCD 0.90",
      ScatterDiff= mean((Sall-S_mcd90@cov)^2),
      LocationDiff= mean((Sall_mean-S_mcd90@center)^2),
      alpha=0.90, method="MCD"
    ))
}    
   write.csv(cov_summary, file = paste("results/covsummaryLandsharc.csv", sep=""))
``` 


### Loop through each dataset
Evaluate empirical power

```{r}
summarydf <- NULL
alpha=c(0.75, 0.90)
  # This is the proportion of points used in the MCD calculation

  for (i in 1:length(filelist)){
    #i=21
    print(c(j, i, filelist[i]))
    infile <- paste(headdir, filelist[i], sep="")
    outfile <- paste(resultsdir, filelist[i], sep="")
    dat <- read.table(infile, header=TRUE)
    dat2 <- dat[dat$UseSNP,]
    
    ### Get stats based on covmat of all the data
    dat.out.defaultS <- Getdf(dat2, cols)
    colnames(dat.out.defaultS)[(ncol(dat.out.defaultS)-5):
                                 ncol(dat.out.defaultS)] <-
      c("pcs.default","Hcd.default", "Md.default", 
        "Hd.default", "Kd.default", "Nd.default")
    
    #head(dat.out.defaultS)
    #dim(dat.out)
    
    p.ranks <- 1-apply(dat2[,cols], 2, rank)/(nrow(dat2)+1)
    min(p.ranks)
    max(p.ranks)
    
    dat.out.defaultS$dcms.ranks <- DCMS(p.ranks)
      
      # Covariance of all loci
      Sall <- cov(dat2[,cols])
      
    for (j in seq_along(alpha)){
      # Covariance of MCD
      S_mcd <- CovNAMcd(dat2[,cols], alpha=alpha[j])
      #sum(S_mcd2@raw.wt) # this should be alpha*number rows in dat2
      
      # Compare cov of neutral data to cov_mcd of all data
      neut <- as.numeric(log(abs(Sneut)))
      all <- as.numeric(log(abs(Sall)))
      mcd <- as.numeric(log(abs(S_mcd@cov)))
      
      # Calculate the proportion of neutral/selected loci identified as robust (non-outliers)
      ProportionNeutralMCDRobust <- sum(dat2$s_high[S_mcd@raw.wt==1]==0)/sum(S_mcd@raw.wt==1)
      ProportionS0.005MCDRobust <- sum(dat2$s_high[S_mcd@raw.wt==1]==0.005)/sum(S_mcd@raw.wt==1)
      ProportionS0.01MCDRobust <- sum(dat2$s_high[S_mcd@raw.wt==1]==0.01)/sum(S_mcd@raw.wt==1)
      ProportionS0.1MCDRobust <- sum(dat2$s_high[S_mcd@raw.wt==1]==0.1)/sum(S_mcd@raw.wt==1)
      ### Get stats based on mcd covmat
      dat.out.subset <- Getdf(dat.out.defaultS,cols,S=S_mcd@cov, M=S_mcd@center,  whichstats=c( "md", "hd", "kd", "nd"), subset=which(S_mcd@raw.wt==1))
      
      colnames(dat.out.subset)[(ncol(dat.out.subset)-3):
                                 ncol(dat.out.subset)] <-
      c( "Md.mcd.subset", "Hd.mcd.subset", "Kd.mcd.subset", "Nd.mcd.subset") 
       head(dat.out.subset)
  
      dat.out.subset$dcms.ranks.mcd <- DCMS(p.ranks, subset=which(S_mcd@raw.wt==1))
             
      dat.out <- dat.out.subset
      
      ## remove these columns for this study
      dat.out2 <- dat.out[,-which(names(dat.out) %in% c("LA.All", "SNP.LA2", "xtx.999perc", "bf.999perc", "rho.999perc",
          "xtx.empP", "bf.empP", "rho.empP",
          "xtx.q", "bf.q", "rho.q", "xtx.FDR01",
          "bf.FDR01", "rho.FDR01", "TW.MinusLogP",
          "TW.P", "K5.Zscore", "K5.MinusLogP",
          "K5.P", "K5.999perc", "KTW.999perc",
          "KTW", "L.q.K.5","L.q.K.TW","L.empQ.K.5","L.empQ.K.TW",
          "Lq.K.5.FDR01","Lq.K.TW.FDR01","L.empQ.K.5.FDR0","L.empQ.K.TW.FDR01", "pca.empP.K10S","pca.q.K10S","pca.FDR01.K10S","pca.empP.K20S","pca.q.K20S","pca.FDR01.K20S","pca.empP.K10NS","pca.q.K10NS","pca.FDR01.K10NS", "L.empQ.K.5.FDR01", "pcs", "Hcd"))]
      
      
      dat.out2$MCDalpha <- alpha[j]
      dat.out2$IsRobust <- S_mcd@raw.wt==1
      head(dat.out2)
      write.table(dat.out2,
              paste("data/KatieSims_multivariate/",filelist[i],"_alpha",alpha[j], sep=""), col.names = TRUE, row.names=FALSE)
  
    dat.out <- dat.out2
      
    ### Calculate Empirical Power ###
      out <- data.frame(infile = as.character(infile),
               demog = as.character(dat.out$demog[1]),
               xtx.ep = getEmpPower(dat.out$xtx, dat.out$s_high==0),
               bf.ep = getEmpPower(dat.out$log.bf, dat.out$s_high==0),
               rho.ep = getEmpPower(dat.out$rho, dat.out$s_high==0),
               lfmm.ep = getEmpPower(dat.out$TW.Zscore, dat.out$s_high==0),
               Hcd.ep = getEmpPower(dat.out$Hcd.default, dat.out$s_high==0),
               pcs.ep = getEmpPower(dat.out$pcs.default, dat.out$s_high==0),
               alpha = alpha[j],
               
               Md.default.ep = getEmpPower(dat.out$Md.default, dat.out$s_high==0),
               Hd.default.ep = getEmpPower(dat.out$Hd.default, dat.out$s_high==0),
               Kd.default.ep = getEmpPower(dat.out$Kd.default, dat.out$s_high==0),
               Nd.default.ep = getEmpPower(dat.out$Nd.default, dat.out$s_high==0),
                
               Md.mcd.subset.ep = getEmpPower(dat.out$Md.mcd.subset, dat.out$s_high==0),
               Hd.mcd.subset.ep = getEmpPower(dat.out$Hd.mcd.subset, dat.out$s_high==0),
               Kd.mcd.subset.ep = getEmpPower(dat.out$Kd.mcd.subset, dat.out$s_high==0),
               Nd.mcd.subset.ep = getEmpPower(dat.out$Nd.mcd.subset, dat.out$s_high==0),
               
              dcms.ranks.ep =  getEmpPower(dat.out$dcms.ranks, dat.out$s_high==0),
              
              dcms.ranks.mcd.ep =  getEmpPower(dat.out$dcms.ranks.mcd, dat.out$s_high==0),
               
              Md.mcd.subset.fp = sum(p.adjust(1-returnEmpP(dat.out$Md.mcd.subset[dat.out$s_high==0], dat.out$Md.mcd.subset[S_mcd@raw.wt==1 & dat.out$s_high==0]),method="BH")<0.05)/9900,
              
               ProportionNeutralMCDRobust,
               ProportionS0.005MCDRobust,
               ProportionS0.01MCDRobust,
               ProportionS0.1MCDRobust
      )
    if (i==1 & j==1){
      write.table(out, file = paste(resultsdir,"LandsharcSummary2.txt", sep=""), append=FALSE, col.names=TRUE, row.names=FALSE)
    }else{
        write.table(out, file = paste(resultsdir,"LandsharcSummary2.txt",sep=""), append=TRUE, col.names=FALSE, row.names=FALSE) 
                  }
    #summarydf <- rbind(summarydf,out)
  } # end loop through alpha
} # end loop through files
#write.table(summarydf,file = , sep=""))
```
